src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 * @Vich\Uploadable
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="post")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="images", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $imageSize;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function serialize()
    {
        $this->imageFile = base64_encode($this->imageFile);
    }

    public function unserialize($serialized)
    {
        $this->imageFile = base64_decode($this->imageFile);

    }

    public function bsonSerialize()
    {
        // TODO: Implement bsonSerialize() method.
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @Vich\Uploadable
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Last_name;

    /**
     * @ORM\Column(type="date")
     */
    private $birth_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alternance_job;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user")
     */
    private $post;

    /**
     * @ORM\ManyToOne(targetEntity=Group::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $group_name;

    // ... other fields

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="images", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="user", orphanRemoval=true)
     */
    private $images;

    public function __construct()
    {
        $this->post = new ArrayCollection();
        $this->updatedAt = new \DateTime();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->Last_name;
    }

    public function setLastName(string $Last_name): self
    {
        $this->Last_name = $Last_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAlternanceJob(): ?string
    {
        return $this->alternance_job;
    }

    public function setAlternanceJob(string $alternance_job): self
    {
        $this->alternance_job = $alternance_job;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPost(): Collection
    {
        return $this->post;
    }

    public function addPost(Post $post): self
    {
        if (!$this->post->contains($post)) {
            $this->post[] = $post;
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->post->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    public function getGroupName(): ?Group
    {
        return $this->group_name;
    }

    public function setGroupName(?Group $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password
            //......
        ];
    }

    public function __unserialize(array $serialized): User
    {
        $this->id = $serialized['id'];
        $this->email = $serialized['email'];
        $this->password = $serialized['password'];
        // .....
        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setUserId($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getUserId() === $this) {
                $image->setUserId(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Images;
use App\Entity\Post;
use App\Entity\User;
use App\Form\AjoutPostFormType;
use App\Form\AvatarType;
use App\Form\ImagesType;
use App\Form\UserSearchType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Form\UserType;

class UserController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/user", name="user")
     */
    public function index(Request $request, Security $security,UserInterface $user, EntityManagerInterface $entityManager):Response
    {
        $id = $user->getId();

        $avatar = $this->createForm(AvatarType::class, $user);
        $avatar->handleRequest($request);

        if ($avatar->isSubmitted() && $avatar->isValid()){
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($user);
            $doctrine->flush();

            $this->addFlash('message', 'Votre image de profil a été modifié');
            return $this->redirectToRoute('user');
        }

        $post = new Post();
        $post->setCreatedAt(date_create('now'));


        $form = $this->createForm(AjoutPostFormType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $post->setUser($this->getUser());
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($post);
            $doctrine->flush();

            $this->addFlash('message', 'Votre post a bien été publié');
            return $this->redirectToRoute('user');
        }

        $image = new Images();
        $image->setUser($this->security->getUser());
        $formImage = $this->createForm(ImagesType::class, $image);
        $formImage->handleRequest($request);

        if ($formImage->isSubmitted() && $formImage->isValid()) {
            $entityManager->persist($image);
            $entityManager->flush();

            return $this->redirectToRoute('user', [], Response::HTTP_SEE_OTHER);
        }

        $posts = $this->getDoctrine()->getRepository(Post::class)->findBy(array('user' => $id), ['id' => 'DESC']);
        return $this->render('user/index.html.twig', [
            'id' => $id,
            'avatar' => $avatar->createView(),
            'posts' => $posts,
            'postForm' => $form->createView(),
            'imageForm' => $formImage->createView(),
        ]);
    }

    public function search(): Response
    {
        $search = $this->createForm( UserSearchType::class);

        return $this->render('user/search.html.twig', [
            'searchform' => $search->createView()
        ]);
    }

    /**
     * @Route("user/{id}", name="one_user", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/oneUser.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/search", name="search")
     */

    public function handleSearch(Request $request ): Response
    {

        $name = $request->request->get('user_search')['search'];

        $result = $this->getDoctrine()->getRepository(User::class)->findByExampleField($name);

        return $this->render('user/showSearch.html.twig', [
            'users' => $result
        ]);
    }

    /**
     * @Route("/update", name="update")
     */

    public  function update(Request $request, Security  $security, UserInterface  $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($user);
            $doctrine->flush();

            $this->addFlash('message', 'Votre post a bien été publié');
            return $this->redirectToRoute('user');
        }

        return $this->render('user/update.html.twig', [
            'updateUserForm' => $form->createView(),
        ]);
    }
}

templates/user/index.html.twig
{% extends 'composants/navbar.html.twig' %}

{% block title %}{{ app.user.firstName }} {{ app.user.lastName }}{% endblock %}

{% block body %}
    {% apply inline_css %}
    <html>
<head>
    <style>
        .cadre {
            width: 200px;
            margin-bottom: 1rem;
        }
        .cadre > img {
            border-radius: 100px;
            max-height: 200px;
        }
        .btn-outline {
            color: #F57C47;
            border: 1px solid #F57C47;
        }
        .violet {
            color: #8B9DF3;
            border: 1px solid #8B9DF3;
            width: 100%;
        }
        .align {
            margin-top: 38px;
        }
        .post {
            background-color: rgb(245, 124, 71, 30%);
            padding: 2rem;
            border-radius: 8px;
        }
        .btn-post {
            background-color: #F57C47;
            color: white;
        }
        .marginTop {
            margin-top: 2rem;
        }
        .photos {
            padding: 0;
        }
        .photo:hover {
            transition: 0.2s;
            opacity: 30%;
        }
    </style>
</head>
    <div style=" margin-top: 5rem; padding: 2rem " class="marginDiv">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <figure class="cadre">
                            <img src="{{ asset("images/" ~ app.user.imageName)}}" alt={{ app.user.imageName }} width="100%">
                    </figure>
                        {{ form_start(avatar) }}
                                <div>
                                    <div class="row">
                                        <div class="col-9">
                                            {{ form_row(avatar.imageFile, {'attr': {'class': 'form-control'}}) }}
                                        </div>
                                        <div class="col-3">
                                            <button type="submit" class="btn btn-outline violet">Valider</button>
                                        </div>
                                    </div>
                                </div>
                        {{ form_end(avatar) }}
                    <h1>{{ app.user.firstName }} {{ app.user.lastName }}</h1>
                    <hr/>
                    <h3>Options</h3>
                    <a class="btn btn-outline me-2" type="button" href="{{ path('update') }}">Modifier mes informations</a>
                    <br/>

                    <hr/>
                    <h3>Vos photos</h3>
                    <br/>
                    <div class="container photos">
                        <div class="row">
                            <div class="col-12">
                                {{ form_start(imageForm) }}
                                {{ form_row(imageForm.imageFile, {'attr': {'class': 'form-control'}}) }}
                                <button class="btn btn-post">Ajouter</button>
                                {{ form_end(imageForm)}}
                            </div>
                            {% for image in app.user.images  %}
                                <div class="col-6 marginTop photo">
                                    <a href="{{ path('images_show', {'id': image.id}) }}">
                                        <img src="{{ asset("images/" ~ image.imageName)}}" alt={{ image.imageName }} width="100%">
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    {% for message in app.flashes('message') %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                    <div class="post">
                        {{ form_start(postForm)}}
                        {{ form_row(postForm.name)}}
                        {{ form_row(postForm.imageFile, { 'attr': {'class': 'form-control'}})}}
                        <button class="btn btn btn-post">Poster</button>
                        {{ form_end(postForm) }}
                    </div>
                    {% for post in posts %}
                        <div class="list-group">
                            <div class="container">
                                <a href="#" class="list-group-item list-group-item-action" aria-current="true" style="margin-top: 50px">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ post.user.firstName }}</h5>
                                        <small>{{ post.createdAt|date('d-m-Y') }}</small>
                                    </div>
                                    <div class="d-flex w-100 justify-content-between">
                                        <p class="mb-1">{{ post.name }}</p>
                                        {% if post.imageName %}
                                            <img src="{{ asset("images/" ~ post.imageName)}}" alt={{ post.imageName }} width="100px">
                                        {% endif %}
                                    </div>
                                    <small>{{ post.user.city }}</small>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endapply %}

{% endblock %}

templates/user/oneUser.html.twig
{% extends 'composants/navbar.html.twig' %}

{% block title %}{{ app.user.firstName }} {{ app.user.lastName }}{% endblock %}

{% block body %}
    {% apply inline_css %}
        <html>
        <head>
            <style>
                .cadre {
                    width: 200px;
                    margin-bottom: 1rem;
                }
                .cadre > img {
                    border-radius: 100px;
                    max-height: 200px;
                }
                .btn-outline {
                    color: #F57C47;
                    border: 1px solid #F57C47;
                }
                .violet {
                    color: #8B9DF3;
                    border: 1px solid #8B9DF3;
                }
                .align {
                    margin-top: 38px;
                }
                .post {
                    background-color: rgb(245, 124, 71, 30%);
                    padding: 2rem;
                    border-radius: 8px;
                }
                .btn-post {
                    background-color: #F57C47;
                    color: white;
                }
                .marginTop {
                    margin-top: 2rem;
                }
                .photos {
                    padding: 0;
                }
                .photo:hover {
                    transition: 0.2s;
                    opacity: 30%;
                }
            </style>
        </head>
        <div style=" margin-top: 5rem; padding: 2rem " class="marginDiv">
            <div class="container">
                <div class="row">
                    <div class="col-4">
                        <figure class="cadre">
                            <img src="{{ asset("images/" ~ user.imageName)}}" alt={{ user.imageName }} width="100%">
                        </figure>
                        <h1>{{ user.firstName }} {{ user.lastName }}</h1>
                        <br/>
                        <hr/>
                        <h3>Photos</h3>
                        <div class="container photos">
                            <div class="row">
                                {% for image in user.images  %}
                                    <div class="col-6 photo" style="margin-top: 2rem">
                                        <a href="{{ path('images_show', {'id': image.id}) }}">
                                            <img src="{{ asset("images/" ~ image.imageName)}}" alt={{ image.imageName }} width="100%">
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-8">
                        {% for post in user.post %}
                            <div class="list-group">
                                <div class="container">
                                    <a href="#" class="list-group-item list-group-item-action" aria-current="true" style="margin-top: 50px">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="mb-1">{{ post.user.firstName }}</h5>
                                            <small>{{ post.createdAt|date('d-m-Y') }}</small>
                                        </div>
                                        <div class="d-flex w-100 justify-content-between">
                                            <p class="mb-1">{{ post.name }}</p>
                                            {% if post.imageName %}
                                                <img src="{{ asset("images/" ~ post.imageName)}}" alt={{ post.imageName }} width="100px">
                                            {% endif %}
                                        </div>
                                        <small>{{ post.user.city }}</small>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endapply %}

{% endblock %}

templates/user/search.html.twig
 {{ form_start(searchform, {
     'attr': {
        'action': path('search')
        }
    })
 }}
<div class="row">
    <div class="col-8">
        {{ form_widget(searchform.search)}}
    </div>
    <div class="col-4 chercher">
        <button class="btn btn-outline violet" type="submit">Chercher</button>
    </div>
</div>
 {{ form_end(searchform)}}

templates/user/showSearch.html.twig
{% extends 'composants/navbar.html.twig' %}

{% block title %}Résultat de votre recherche{% endblock %}

{% block body %}
        {% apply inline_css %}
<html>
<head>
    <style>
        .marginDiv {
            margin-top: 5rem;
        }
        .violet {
            border: 1px solid #8b9df3;
            color: #8b9df3;
            width: 100%;
        }
        .violet:hover {
            border: 1px solid #f57c47;
            color: #f57c47;
        }
        .chercher {
            display: flex;
            justify-content: right;
        }
    </style>
</head>

    <div class="marginDiv">
        <div class="container col-6">
            {{ render(controller(
                'App\\Controller\\UserController::search',
            )) }}
        </div>

        {% for user in users %}
            <div class="list-group">
                <div class="container col-6">
                    <a href="{{ path('one_user', {'id': user.id}) }}" class="list-group-item list-group-item-action" aria-current="true" style="margin-top: 50px">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ user.firstName }} - {{ user.lastName }}</h5>
                            <small>{{ user.birthDate|date('d-m-Y') }}</small>
                        </div>
                        <div class="d-flex w-100 justify-content-between">
                            <p class="mb-1">{{ user.alternanceJob }}</p>
                            {% if user.imageName %}
                                <img src="{{ asset("images/" ~ user.imageName)}}" alt={{ user.imageName }} width="10%">
                            {% endif %}
                        </div>
                        <small>{{ user.city }}</small>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endapply %}

{% endblock %}

templates/user/update.html.twig
{% extends 'composants/navbar.html.twig' %}

{% block title %}{{ app.user.firstName }} {{ app.user.lastName }}{% endblock %}

{% block body %}
    {% apply inline_css %}
    <html>
    <head>
        <style>
            .vich-image > a > img {
                width: 20%;
            }
            .vich-image > .custom-file > input > button {
                background-color: black;
                color: white;
            }
            .btn-outline {
                color: white;
                background-color: #F57C47;
            }
            .register {
                background-color: rgb(245, 124, 71, 30%);
                padding: 2rem;
                border-radius: 8px;
            }
            .form-group {
                margin: 0.5rem 0;
            }
            h1 {
                font-size: 3rem;
                color: #8b9df3;
            }
        </style>
    </head>
    <div style=" margin-top: 3rem; padding: 2rem " class=" container">
        {{ form_start(updateUserForm) }}
        <h1>Modifier mes informations</h1>
        <div class="container row register">
            <div class="col-6">
                {{ form_row(updateUserForm.email) }}
                {{ form_row(updateUserForm.firstName) }}
                {{ form_row(updateUserForm.lastName) }}
                {{ form_row(updateUserForm.birthDate) }}
                {{ form_row(updateUserForm.address) }}
                {{ form_row(updateUserForm.city) }}

            </div>
            <div class="col-6">

                {{ form_row(updateUserForm.alternanceJob) }}
                {{ form_row(updateUserForm.groupName) }}
                <br/>
                <button type="submit" class="btn btn-outline btn-lg">Valdier</button>
            </div>
        </div>
        {{ form_end(updateUserForm) }}


    {% endapply %}

{% endblock %}